tap 'bfontaine/languages', 'git@github.com:bfontaine/homebrew-languages.git'
tap 'bfontaine/portlivecheck', 'git@github.com:bfontaine/homebrew-portlivecheck.git'
tap 'bfontaine/powersearch', 'gh:bfontaine/homebrew-powersearch.git'
tap 'bfontaine/search', 'git@github.com:bfontaine/homebrew-search.git'
tap 'bfontaine/tools', 'git@github.com:bfontaine/homebrew-tools.git'
tap 'bfontaine/utils', 'git@github.com:bfontaine/homebrew-utils.git'
tap 'caskroom/cask', 'git@github.com:caskroom/homebrew-cask.git'
tap 'caskroom/versions', 'git@github.com:caskroom/homebrew-versions.git'
tap 'homebrew/aliases', 'git@github.com:Homebrew/homebrew-aliases.git'
tap 'homebrew/apache', 'git@github.com:Homebrew/homebrew-apache.git'
tap 'homebrew/boneyard', 'git@github.com:Homebrew/homebrew-boneyard.git'
tap 'homebrew/bundle', 'git@github.com:Homebrew/homebrew-bundle.git'
tap 'homebrew/command-not-found', 'git@github.com:Homebrew/homebrew-command-not-found.git'
tap 'homebrew/core', 'git@github.com:Homebrew/homebrew-core.git'
tap 'homebrew/dev-tools', 'git@github.com:Homebrew/homebrew-dev-tools.git'
tap 'homebrew/nginx', 'git@github.com:Homebrew/homebrew-nginx.git'
tap 'homebrew/php', 'git@github.com:Homebrew/homebrew-php.git'
tap 'homebrew/science', 'git@github.com:Homebrew/homebrew-science.git'
brew 'ack'
brew 'adns'
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'git'
brew 'openssl'
brew 'pkg-config'
brew 'gdbm'
brew 'readline'
brew 'sqlite'
brew 'python'
brew 'autoconf'
brew 'automake'
brew 'base64'
brew 'bash'
brew 'bash-completion'
brew 'bison'
brew 'boost'
brew 'browser'
brew 'cask'
brew 'cgrep'
brew 'clasp'
brew 'cmake'
brew 'coreutils'
brew 'ctags'
brew 'curl', args: ['with-openssl']
brew 'daemontools'
brew 'libgpg-error'
brew 'libassuan'
brew 'libgcrypt'
brew 'libksba'
brew 'pth'
brew 'dirmngr'
brew 'exiftool'
brew 'lame'
brew 'x264'
brew 'xvid'
brew 'ffmpeg'
brew 'figlet'
brew 'findutils'
brew 'flac'
brew 'fswatch'
brew 'gmp'
brew 'mpfr'
brew 'gawk'
brew 'gcc'
brew 'jpeg'
brew 'libtiff'
brew 'giflib'
brew 'gifsicle'
brew 'git-extras'
brew 'gmp@4'
brew 'gnu-sed'
brew 'libtasn1'
brew 'libunistring'
brew 'nettle'
brew 'p11-kit'
brew 'libusb'
brew 'npth'
brew 'pinentry'
brew 'gnupg'
brew 'go'
brew 'gpg-agent'
brew 'gringo'
brew 'gsl'
brew 'icu4c'
brew 'htop-osx'
brew 'hunspell'
brew 'libtool'
brew 'perl'
brew 'xz'
brew 'imagemagick'
brew 'picocom'
brew 'ino'
brew 'jpegoptim'
brew 'oniguruma'
brew 'jq'
brew 'leiningen'
brew 'libogg'
brew 'libvorbis'
brew 'libxml2'
brew 'libyaml'
brew 'llvm'
brew 'lua'
brew 'mas'
brew 'md5sha1sum'
brew 'mercurial'
brew 'mongo-c-driver'
brew 'moreutils'
brew 'mtr'
brew 'multitail'
brew 'ocaml', args: ['with-x11']
brew 'optipng'
brew 'osmium-tool'
brew 'p7zip'
brew 'pandoc'
brew 'patchutils'
brew 'pigz'
brew 'pngcrush'
brew 'python3'
brew 'rename'
brew 'rlwrap'
brew 'ruby'
brew 'rust'
brew 'safe-rm'
brew 'shpotify'
brew 'sl'
brew 'sloccount'
brew 'spoof-mac'
brew 'ssh-copy-id'
brew 'tree'
brew 'unar'
brew 'vim'
brew 'wget'
brew 'youtube-dl'
brew 'yuicompressor'
brew 'z', args: ['HEAD']
brew 'bfontaine/utils/iwc'
brew 'bfontaine/utils/mvb'
brew 'bfontaine/utils/rfc'
brew 'bfontaine/utils/up'
cask 'emacs'
cask 'java'
cask 'launchrocket'
cask 'poedit'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'skim'
cask 'skype'
cask 'virtualbox'
mas 'Amphetamine', id: 937984704
mas 'Keynote', id: 409183694
mas 'MoneyWiz 2', id: 949724400
mas 'Textual 5', id: 896450579
mas 'Xcode', id: 497799835
