tap "bfontaine/languages", "git@github.com:bfontaine/homebrew-languages.git"
tap "bfontaine/portlivecheck", "git@github.com:bfontaine/homebrew-portlivecheck.git"
tap "bfontaine/powersearch", "gh:bfontaine/homebrew-powersearch.git"
tap "bfontaine/search", "git@github.com:bfontaine/homebrew-search.git"
tap "bfontaine/tools", "git@github.com:bfontaine/homebrew-tools.git"
tap "bfontaine/utils", "git@github.com:bfontaine/homebrew-utils.git"
tap "caskroom/cask", "git@github.com:caskroom/homebrew-cask.git"
tap "caskroom/versions", "git@github.com:caskroom/homebrew-versions.git"
tap "homebrew/aliases", "git@github.com:Homebrew/homebrew-aliases.git"
tap "homebrew/apache", "git@github.com:Homebrew/homebrew-apache.git"
tap "homebrew/boneyard", "git@github.com:Homebrew/homebrew-boneyard.git"
tap "homebrew/bundle", "git@github.com:Homebrew/homebrew-bundle.git"
tap "homebrew/command-not-found", "gh:Homebrew/homebrew-command-not-found.git"
tap "homebrew/core", "git@github.com:Homebrew/homebrew-core.git"
tap "homebrew/dev-tools", "git@github.com:Homebrew/homebrew-dev-tools.git"
tap "homebrew/nginx", "git@github.com:Homebrew/homebrew-nginx.git"
tap "homebrew/php", "git@github.com:Homebrew/homebrew-php.git"
tap "homebrew/science", "git@github.com:Homebrew/homebrew-science.git"
cask "java"
brew "ack"
brew "autoconf"
brew "automake"
brew "base64"
brew "readline"
brew "bash"
brew "bash-completion"
brew "bison"
brew "browser"
brew "cask"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "curl", args: ["with-openssl"]
brew "daemontools"
brew "exiftool"
brew "lame"
brew "perl"
brew "git"
brew "x264"
brew "xvid"
brew "ffmpeg"
brew "figlet"
brew "findutils"
brew "libpng"
brew "freetype"
brew "gmp"
brew "mpfr"
brew "gawk"
brew "gcc"
brew "gdbm"
brew "gettext"
brew "giflib"
brew "gifsicle"
brew "git-extras"
brew "gnu-sed"
brew "go"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "pinentry"
brew "pth"
brew "gpg-agent"
brew "htop-osx"
brew "hunspell"
brew "icu4c"
brew "jpeg"
brew "libtiff"
brew "libtool"
brew "xz"
brew "imagemagick"
brew "picocom"
brew "ino"
brew "jpegoptim"
brew "oniguruma"
brew "jq"
brew "jruby"
brew "leiningen"
brew "libogg"
brew "openssl"
brew "libunistring"
brew "libusb"
brew "libvorbis"
brew "libxml2"
brew "libyaml"
brew "lua"
brew "mas"
brew "md5sha1sum"
brew "sqlite"
brew "python"
brew "mercurial"
brew "mongo-c-driver"
brew "moreutils"
brew "mtr"
brew "multitail"
brew "node"
brew "ocaml"
brew "optipng"
brew "p7zip"
brew "pandoc"
brew "patchutils"
brew "pcre"
brew "pigz"
brew "pkg-config"
brew "pngcrush"
brew "python3"
brew "rename"
brew "rlwrap"
brew "ruby"
brew "rust"
brew "safe-rm"
brew "shpotify"
brew "sl"
brew "sloccount"
brew "spoof-mac"
brew "ssh-copy-id"
brew "tree"
brew "unar"
brew "vim"
brew "wget"
brew "youtube-dl"
brew "yuicompressor"
brew "z", args: ["HEAD"]
brew "bfontaine/utils/gzsize"
brew "bfontaine/utils/iwc"
brew "bfontaine/utils/mvb"
brew "bfontaine/utils/rfc"
brew "bfontaine/utils/up"
cask "emacs"
cask "launchrocket"
cask "poedit"
cask "qlcolorcode"
cask "qlmarkdown"
cask "quicklook-json"
cask "skim"
cask "skype"
cask "virtualbox"
mas "Amphetamine", id: 937984704
mas "Keynote", id: 409183694
mas "MoneyWiz 2", id: 949724400
mas "Textual 5", id: 896450579
mas "Xcode", id: 497799835
