{:user {:plugins [[lein-cloverage                    "1.0.2"]
                  [lein-fore-prob                    "0.1.2"]
                  [lein-ancient                      "0.6.10"]
                  [jonase/eastwood                   "0.2.3"]
                  [com.jakemccrary/lein-test-refresh "0.3.4"]
                  [lein-pprint                       "1.1.1"]
                  [lein-kibit                        "0.1.2"]
                  [cider/cider-nrepl                 "0.12.0"]
                  [venantius/ultra                   "0.4.1"]]
        :signing {:gpg-key "E5B26621"}}}
